export const MAIN_ROUTE = '/'
export const USER_ROUTE = '/user-:id'
export const SUBJECT_ROUTE = '/subject'
export const DIARY_ROUTE = '/diary'
export const SCHOOL_ROUTE = '/school'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const ALL_MARKS = '/all-marks'
export const ONE_SUBJECT_MARKS = '/subject-'
export const ALL_USERS_PAGE = '/all-users'
export const ALL_ADMINS = '/all-admin'
export const ALL_TEACHERS = '/all-teacher'
export const ALL_PUPILS = '/all-pupil'
export const ALL_CLASSROOMS = '/classroom'
export const CLASSROOM_ROUTE = '/classroom-:id'

